name: spectropy release
run-name: ${{ github.actor }} is publishing release ${{ github.ref_name }}
on:
  release:
    types: [published, released]
  workflow_dispatch:
jobs:
  sha256:
    name: sha256
    runs-on: ubuntu-latest
    steps:
      - name: tgz url
        run: echo "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"
      - name: tgz sha256 
        run: curl -sL "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz" | shasum -a 256 | cut -d " " -f 1
      - name: dmg url
        run: echo "${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.ref_name }}/Spectropy.dmg"
      - name: dmg sha256
        run: curl -sL "${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.ref_name }}/Spectropy.dmg" | shasum -a 256 | cut -d " " -f 1
        
